version: '3'

services:
  api:
    container_name: my-books-api-prod
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  frontend-prod:
    container_name: my-books-frontend-prod
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 1337:80
