version: '3'

services:
  discovery-service:
    container_name: discovery_service_dev
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  api:
    container_name: my_books_api_dev
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    links:
      - "discovery-service:eureka"
  api-client:
    container_name: my_books_api_client_dev
    build:
      context: api-client
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    links:
      - "discovery-service:eureka"
  frontend:
    container_name: my_books_frontend_dev
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
