server:
  port: 8081

spring:
  mvc:
    async:
      request-timeout: 300
  application:
    name: my-books-api
  profiles:
    active: local

---
spring:
  profiles: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
