server:
  port: 8082

spring:
  mvc:
    async:
      request-timeout: 300
  application:
    name: my-books-api-client
  profiles:
    active: local

my-books-api:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

---
spring:
  profiles: local

eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker

eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
